name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Otomatis jalan saat ada push ke branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # Pastikan channelID adalah 'live'
          channelId: live
          # Menggunakan Project ID Anda: lontong-mm
          projectId: lontong-mm 
        env:
          # Menggunakan Secret Token yang telah kita simpan
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_TOKEN }}
